import z from 'zod/v4';
import { NamePropertySchema } from './NamePropertySchema';

export const TAppearanceSchema = z.looseObject({
    nmHead: NamePropertySchema,
    iGender: z.number().int(),
    iRace: z.number().int(),
    nmHaircut: NamePropertySchema,
    iHairColor: z.number().int(),
    iFacialHair: z.number().int(),
    nmBeard: NamePropertySchema,
    iSkinColor: z.number().int(),
    iEyeColor: z.number().int(),
    nmFlag: NamePropertySchema,
    iVoice: z.number().int(),
    iAttitude: z.number().int(),
    iArmorDeco: z.number().int(),
    iArmorTint: z.number().int(),
    iArmorTintSecondary: z.number().int(),
    iWeaponTint: z.number().int(),
    iTattooTint: z.number().int(),
    nmWeaponPattern: NamePropertySchema,
    nmPawn: NamePropertySchema,
    nmTorso: NamePropertySchema,
    nmArms: NamePropertySchema,
    nmLegs: NamePropertySchema,
    nmHelmet: NamePropertySchema,
    nmEye: NamePropertySchema,
    nmTeeth: NamePropertySchema,
    nmFacePropLower: NamePropertySchema,
    nmFacePropUpper: NamePropertySchema,
    nmPatterns: NamePropertySchema,
    nmVoice: NamePropertySchema,
    nmLanguage: NamePropertySchema,
    nmTattoo_LeftArm: NamePropertySchema,
    nmTattoo_RightArm: NamePropertySchema,
    nmScars: NamePropertySchema,
    nmTorso_Underlay: NamePropertySchema,
    nmArms_Underlay: NamePropertySchema,
    nmLegs_Underlay: NamePropertySchema,
    nmFacePaint: NamePropertySchema,
    nmLeftArm: NamePropertySchema.optional(),
    nmRightArm: NamePropertySchema.optional(),
    nmLeftArmDeco: NamePropertySchema.optional(),
    nmRightArmDeco: NamePropertySchema.optional(),
    nmLeftForearm: NamePropertySchema.optional(),
    nmRightForearm: NamePropertySchema.optional(),
    nmThighs: NamePropertySchema.optional(),
    nmShins: NamePropertySchema.optional(),
    nmTorsoDeco: NamePropertySchema.optional(),
    bGhostPawn: z.boolean(),
});
