import z from 'zod/v4';
import { NameSchema } from '../Properties/Name/NameSchema';

export const TAppearanceSchema = z.looseObject({
    nmHead: NameSchema,
    iGender: z.number().int(),
    iRace: z.number().int(),
    nmHaircut: NameSchema,
    iHairColor: z.number().int(),
    iFacialHair: z.number().int(),
    nmBeard: NameSchema,
    iSkinColor: z.number().int(),
    iEyeColor: z.number().int(),
    nmFlag: NameSchema,
    iVoice: z.number().int(),
    iAttitude: z.number().int(),
    iArmorDeco: z.number().int(),
    iArmorTint: z.number().int(),
    iArmorTintSecondary: z.number().int(),
    iWeaponTint: z.number().int(),
    iTattooTint: z.number().int(),
    nmWeaponPattern: NameSchema,
    nmPawn: NameSchema,
    nmTorso: NameSchema,
    nmArms: NameSchema,
    nmLegs: NameSchema,
    nmHelmet: NameSchema,
    nmEye: NameSchema,
    nmTeeth: NameSchema,
    nmFacePropLower: NameSchema,
    nmFacePropUpper: NameSchema,
    nmPatterns: NameSchema,
    nmVoice: NameSchema,
    nmLanguage: NameSchema,
    nmTattoo_LeftArm: NameSchema,
    nmTattoo_RightArm: NameSchema,
    nmScars: NameSchema,
    nmTorso_Underlay: NameSchema,
    nmArms_Underlay: NameSchema,
    nmLegs_Underlay: NameSchema,
    nmFacePaint: NameSchema,
    nmLeftArm: NameSchema,
    nmRightArm: NameSchema,
    nmLeftArmDeco: NameSchema,
    nmRightArmDeco: NameSchema,
    nmLeftForearm: NameSchema,
    nmRightForearm: NameSchema,
    nmThighs: NameSchema,
    nmShins: NameSchema,
    nmTorsoDeco: NameSchema,
    bGhostPawn: z.boolean(),
});
